### ISSUE TITLE
'Overcooked_LLMA_V4' object has no attribute 'seed'

### ISSUE THREAD

**Issue by paulzyzy** [WeihaoTan/TWOSOME#13]
Hi, when I run sh scripts/tomato_salad_ppo_llm.sh, I meet the following error:
Traceback (most recent call last):
  File "/home/yuz23046/TWOSOME/twosome/overcooked/ppo_llm_pomdp.py", line 184, in <module>
    envs = gym.vector.SyncVectorEnv(
  File "/home/yuz23046/miniconda3/envs/twosome/lib/python3.9/site-packages/gym/vector/sync_vector_env.py", line 52, in __init__
    self.envs = [env_fn() for env_fn in env_fns]
  File "/home/yuz23046/miniconda3/envs/twosome/lib/python3.9/site-packages/gym/vector/sync_vector_env.py", line 52, in <listcomp>
    self.envs = [env_fn() for env_fn in env_fns]
  File "/home/yuz23046/TWOSOME/twosome/overcooked/ppo_llm_pomdp.py", line 126, in thunk
    env.seed(seed)
  File "/home/yuz23046/miniconda3/envs/twosome/lib/python3.9/site-packages/gym/core.py", line 241, in __getattr__
    return getattr(self.env, name)
  File "/home/yuz23046/miniconda3/envs/twosome/lib/python3.9/site-packages/gym/core.py", line 241, in __getattr__
    return getattr(self.env, name)
  File "/home/yuz23046/miniconda3/envs/twosome/lib/python3.9/site-packages/gym/core.py", line 241, in __getattr__
    return getattr(self.env, name)
AttributeError: 'Overcooked_LLMA_V4' object has no attribute 'seed'

**Comment by WeihaoTan** [comment]
Hi. Which version of gym do you use? Did you install the libraries with the requirement.txt?
